% Arnoldi process
function [V,H] = Arnoldi(A,b,x0,restartm)
% Input: restartm is the restart parameter
    
    [m, ~] = size(A);
    R = Inf(m,m);
    H = zeros(m+1,m);V = zeros(m,m+1);%A*V=V*H
    
    % V1 = r0./norm(r0)
    r0 = b-A*x0;
    V(:,1) = r0./norm(r0);
    for j = 1:restartm
        R(:,j) = A*V(:,j);
        for i = 1:j
            H(i,j) = R(:,j)'*V(:,i);
            R(:,j) = R(:,j) - H(i,j)*V(:,i);
        end
        H(j+1,j) = norm(R(:,j));
        if abs(H(j+1,j)) < 1e-10
            sprintf('done without residual');%Real m is the real m generated by H(j+1,j) = 0. 
            break;
        else
            V(:,j+1) = R(:,j)./H(j+1,j);
        end
    end
    
    H = H(1:j+1,1:j);
    V = V(:,1:j);
end

